### ISSUE TITLE
Compilation failure after v2.4.1 -> v2.6.0 version bump. Possible go-webview2 problem.

### ISSUE THREAD

**Issue by Krzysztofz01** [wailsapp/wails#2928]
### Description

The software I'm working on uses the `v2.4.1` version of Wails. In today's attempt to update Wails to `v2.6.0` and all dependencies using the `go get -u github.com/wailsapp/wails/v2` command, a problem occurred.

```
...
Building application for development...
Done.
  • Generating application assets: Done.
  • Compiling application: # github.com/wailsapp/wails/v2/internal/frontend/desktop/windows
C:\Users\Krzysztof\go\pkg\mod\github.com\wailsapp\wails\v2@v2.6.0\internal\frontend\desktop\windows\frontend.go:616:95: too many arguments in call to env.CreateWebResourceResponse
        have ([]byte, int, string, string)
        want ([]byte, int, string)

Build error - exit status 1
```

Trying to get to the root of the problem, I noticed that there was an API change in the go-webview2 library. 

```golang
// go-webview2 v1.0.5
func (e *ICoreWebView2Environment) CreateWebResourceResponse(content []byte, statusCode int, reasonPhrase string, headers string) (*ICoreWebView2WebResourceResponse, error)

// go-webview2 v1.0.6
func (e *ICoreWebView2Environment) CreateWebResourceResponse(content []byte, statusCode int, headers string) (*ICoreWebView2WebResourceResponse, error)
```

It looks like Wails version `v2.6.0` is targeting, the wrong version of go-webview2. Manually lowering the go-webview2 version in `go.mod` helped and I was able to build the application, but it seems to me that such a problem should not happen. Or was the migration to a higher version of Wails of my application done in a bad way? 

### To Reproduce

I was not able to reproduce this problem on a new Wails project, which may indicate that the source of the problem was the migration process from `v2.4.1` to `v.2.6.0`.

### Expected behaviour

It seems to me that the very process of updating the project's dependencies and upgrading the version of the CLI Wails tool should be sufficient to update the project and no "manual" changes to `go.mod` should be required. 

### Attempted Fixes

Manually changing the go-webview2 version in `go.mod` from `v1.0.6` to `v1.0.5` solves the problem in my case, but is not required for projects that previously targeted a different version of Wails and the latest `v2` version.

### System Details

```shell
# Wails
Version | v2.6.0

# System
┌────────────────────────────────────┐
| OS           | Windows 10 Pro      |
| Version      | 2009 (Build: 19045) |
| ID           | 22H2                |
| Go Version   | go1.20              |
| Platform     | windows             |
| Architecture | amd64               |
└────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 117.0.2045.31 |
| Nodejs     | N/A          | Installed | 16.14.0       |
| npm        | N/A          | Installed | 8.3.1         |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

The go.mod of `v2.6.0` references the right version of webview2 `v1.0.1` as indicated here: https://github.com/wailsapp/wails/blob/v2.6.0/v2/go.mod#L36

Doing a `go get -u github.com/wailsapp/wails/v2` does also update all indirect dependencies that's why you got a newer version of `go-webview2` and you see this error. Changing the signature of that method was not a good idea with regard to module handling. So we should revert the breaking API change and reintroduce the signature, and release a new version. That should prevent this error.

**Comment by stffabi** [comment]
@leaanthony I've already reverted the breaking api change in go-webview2. Would it be possible for you to create a new release?

**Comment by leaanthony** [comment]
@stffabi - https://github.com/wailsapp/go-webview2/releases/tag/v1.0.7

**Comment by leaanthony** [comment]
@Krzysztofz01 - Please try running `go get -u github.com/wailsapp/wails/v2` again to pull in v1.0.7. This should fix the issue. Let us know how you get on 👍

**Comment by stffabi** [comment]
Awesome thanks @leaanthony for tagging a new release 🙏

**Comment by stffabi** [comment]
The issue is resolved with latest version of go-webview2. Feel free to reopen if you see any further problems. Thanks again for reporting this 🙏 .

**Comment by Krzysztofz01** [comment]
Everything is working properly now. Thank you for your quick response

**Comment by leaanthony** [comment]
Thanks for raising the issue 🙏
