### PR TITLE
fix(v3/linux): repair purego assetserver backend compile errors

### LINKED ISSUE #5550: [v3] purego Linux backend fails to compile
### Description

The purego (CGO-free) Linux backend does not compile in v3.0.0-alpha.98.
```
internal/assetserver/webview/responsewriter_linux_purego.go:128:
  *responseWriter does not implement ResponseWriter (wrong type for method Finish)
    have Finish()
    want Finish() error
internal/assetserver/webview/webkit2_purego.go:36:
  cannot use &iter (*[]byte) as uintptr value in argument to headersIterInit
internal/assetserver/webview/webkit2_purego.go:45:
  cannot use &iter (*[]byte) as uintptr value in argument to iterNext
internal/assetserver/webview/webkit2_purego.go:60:
  cannot use resp (string) as uintptr value in argument to unRef
```

The ResponseWriter interface (responsewriter.go:24) requires Finish() error. Every backend implements that signature except purego — responsewriter_linux_purego.go:128 declares func (rw *responseWriter) Finish() { with no error return. Separately, webkit2_purego.go passes Go pointers/strings where uintptr is expected.

### To Reproduce

GOOS=linux CGO_ENABLED=0 go build -tags purego github.com/wailsapp/wails/v3/pkg/application

### Expected behaviour

-tags purego Linux build compiles, like the cgo/gtk3/darwin/windows backends.

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
Go 1.26.3, wails/v3 alpha.98.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leaanthony**
# Description

First layer of #5550: makes `internal/assetserver/webview` compile (and behave correctly) under `GOOS=linux CGO_ENABLED=0 -tags purego`.

## What was broken

Reproduced with `GOOS=linux CGO_ENABLED=0 go build -tags purego ./pkg/application` — the first failing package was `internal/assetserver/webview`:

- `webkit2_purego.go` registered **six different libwebkit/libsoup functions into the wrong Go function variables** (copy-pasted `&unRef` / `&getUri`), so even where it compiled it would have invoked the wrong C symbols at runtime.
- `webkit_uri_scheme_response_new` was registered as returning `string` instead of a GObject pointer, so the response object was never usable (and `unRef` was handed a Go string).
- `soup_*` symbols were resolved through the **libgtk-3 handle**, which does not link libsoup — they now resolve through the libwebkit2gtk handle, whose dependency chain includes libsoup.
- `SoupMessageHeadersIter` was modelled as a 12-byte buffer with a TODO; libsoup declares it as `gpointer dummy[3]`. Header iteration now uses `*[3]uintptr` storage and `*uintptr` out-params with a manual C-string conversion (purego's automatic string marshalling only applies to by-value arguments, not out-params).
- The bottom half of the file was **raw cgo code** (`undefined: C`, `io`, `unsafe`) implementing a request-body reader that the purego request implementation never calls — `Body()` returns `http.NoBody`. Removed as dead code.
- `responseWriter.Finish()` had drifted from the `ResponseWriter` interface (missing `error` return) and leaked the `GInputStream` it created. A compile-time `var _ ResponseWriter = &responseWriter{}` assertion now prevents future drift.
- `finishWithError` registered `g_error_new_literal` with the wrong arity (4 args instead of 3) and passed a hardcoded quark; it now mirrors the cgo gtk3 implementation.

## Verification

```
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags purego ./internal/assetserver/webview   # OK (failed before)
GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -tags purego ./internal/assetserver/webview   # OK
go vet (same tags/arches)                                                                     # OK
```

## Remaining scope (why this doesn't close #5550)

`pkg/application` still does not compile under purego: the `linuxApp` platform layer (`application_linux.go`, `linux_cgo.go` — ~2,500 lines) has **no purego port**. 19 distinct package symbols (`linuxApp`, `newPlatformApp`, `fatalHandler`, clipboard/menu/systray functions) plus dozens of `linuxWebviewWindow` methods are missing, and shared files have signature drift (`menuAppend`, dialog channel returns). Detailed assessment posted on the issue — completing vs. explicitly gating the experimental purego backend is a maintainer decision.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the general coding style of this project
- [x] I have updated `v3/UNRELEASED_CHANGELOG.md`

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved WebKit request handling on Linux, including HTTP method/header processing and response completion.
  * Fixed request finishing behavior so responses are completed more reliably and stream resources are released safely.
  * Improved error handling for failed responses, making failures cleaner and more consistent.
  * Tightened platform support for the Linux WebView implementation.

### CODE REVIEW

File: v3/internal/assetserver/webview/webkit2_purego.go [hunk 1]
```diff
@@ -1,80 +1,97 @@
...
 	"strings"
+	"unsafe"
 
 	"github.com/ebitengine/purego"
 )
 
+// SoupMessageHeadersType value for response headers
+// (libsoup soup-message-headers.h: REQUEST = 0, RESPONSE = 1, MULTIPART = 2).
+const SOUP_MESSAGE_HEADERS_RESPONSE = 1
+
```
[the remark this answers is not in the document]
Comment (leaanthony) [reply v3/internal/assetserver/webview/webkit2_purego.go:16]: Done — renamed to `soupMessageHeadersResponse` (unexported camelCase) in the latest commit.
