### ISSUE TITLE
[v3] purego Linux backend fails to compile

### ISSUE THREAD

**Issue by RALIST** [wailsapp/wails#5550]
### Description

The purego (CGO-free) Linux backend does not compile in v3.0.0-alpha.98.
```
internal/assetserver/webview/responsewriter_linux_purego.go:128:
  *responseWriter does not implement ResponseWriter (wrong type for method Finish)
    have Finish()
    want Finish() error
internal/assetserver/webview/webkit2_purego.go:36:
  cannot use &iter (*[]byte) as uintptr value in argument to headersIterInit
internal/assetserver/webview/webkit2_purego.go:45:
  cannot use &iter (*[]byte) as uintptr value in argument to iterNext
internal/assetserver/webview/webkit2_purego.go:60:
  cannot use resp (string) as uintptr value in argument to unRef
```

The ResponseWriter interface (responsewriter.go:24) requires Finish() error. Every backend implements that signature except purego — responsewriter_linux_purego.go:128 declares func (rw *responseWriter) Finish() { with no error return. Separately, webkit2_purego.go passes Go pointers/strings where uintptr is expected.

### To Reproduce

GOOS=linux CGO_ENABLED=0 go build -tags purego github.com/wailsapp/wails/v3/pkg/application

### Expected behaviour

-tags purego Linux build compiles, like the cgo/gtk3/darwin/windows backends.

### System Details

```shell
Go 1.26.3, wails/v3 alpha.98.
```

**Comment by leaanthony** [comment]
Thanks for the detailed report — confirmed, and the rot goes deeper than the errors you posted.

**What's fixed:** #5564 repairs `internal/assetserver/webview` under `-tags purego` (your reported errors, plus several latent bugs: six `RegisterLibFunc` calls registering into the wrong function variables, soup symbols resolved through the wrong library handle, a mis-modelled `SoupMessageHeadersIter`, and leftover cgo code). That package now builds and vets cleanly for linux/amd64 and linux/arm64 with `CGO_ENABLED=0`.

**What remains:** `pkg/application` itself has never had a purego platform layer. With `-gcflags=-e` the full error list shows 19 distinct undefined symbols — `linuxApp`, `newPlatformApp`, `fatalHandler`, `clipboardSet/Get`, `getNativeApplication`, the menu item constructors, `newSystemTrayImpl`, dev-tools hooks — plus dozens of missing `linuxWebviewWindow` methods (`close`, `present`, `isMaximised`, `setupSignalHandlers`, …) and signature drift in shared files (`menuAppend`, `attachMenuHandler`, dialog functions now returning channels). The cgo side this would need to mirror (`application_linux.go` + `linux_cgo.go`) is ~2,500 lines.

So `go build -tags purego ./pkg/application` failing isn't a regression — the purego backend is an unfinished experiment (`linux_purego.go` covers roughly the windowing wrappers only) with no CI coverage, which is why it rotted silently.

Options from here:

1. **Complete the port** — mechanical but large (~2–3k lines of purego FFI), and it needs real GTK runtime testing, not just compile checks.
2. **Gate it explicitly** — keep the purego files compiling (post-#5564) but document the backend as experimental/incomplete, and add a CI cross-compile check for the packages that do support it so they can't rot again.

Happy to take on either once there's a direction.
