### PR TITLE
fix(v3): implement BrowserWindow.SetScreen to fix `-tags server` build

### LINKED ISSUE #5262: [v3] -tags server build fails (BrowserWindow missing Window.SetScreen)
Building any Wails v3 application with `-tags server` fails to compile in v3.0.0-alpha.78. The `BrowserWindow` type (defined in `v3/pkg/application/browser_window.go` under `//go:build server`) does not implement the `Window` interface — it's missing `SetScreen(screen *Screen) Window`, which was added to the `Window` interface in #5067.

The bug is also present on the current tip of `v3-alpha`.

### To Reproduce

Any v3 example, e.g. from a fresh checkout:

```bash
cd v3/examples/dock
go build -tags server .

Errors (truncated)
v3/pkg/application/browser_window.go:65:80: cannot use b (variable of type *BrowserWindow) as Window value in return statement: *BrowserWindow does not implement Window (missing method SetScreen)
v3/pkg/application/browser_window.go:74:80: cannot use b (variable of type *BrowserWindow) as Window value in return statement: ...
```

### Expected behavior

`go build -tags server .` succeeds, producing a server-mode binary as documented in `pkg/application/application_server.go.`

### Suggested fix

Add a no-op SetScreen to BrowserWindow that matches the existing no-op pattern in the file (browser windows have no notion of physical screens):

```
func (b *BrowserWindow) SetScreen(screen *Screen) Window { return b }
```

### Why this matters / use case

Server mode is the documented path for running the same Wails app under HTTP for headless test harnesses (Playwright/etc.) and for future hosted deployment. With it broken, projects pinned to alpha.78 cannot use the published task build:server / task run:server workflow without a local fork.

### Environment

Wails CLI Version: v3.0.0-alpha.78
Platform: macOS (Darwin 24.6.0); also reproduces on Linux/Windows because the offending file is platform-agnostic
Go: any recent 1.22+

### PR DESCRIPTION
**Pull request by josh-padnick**
# Description

PR #5067 added `SetScreen(screen *Screen) Window` to the `Window` interface but did not update `BrowserWindow` (the server-mode adapter in `v3/pkg/application/browser_window.go`, gated by `//go:build server`). As a result, `*BrowserWindow` no longer satisfies `Window` and any build with `-tags server` fails to compile, breaking the documented headless / test-automation workflow.

This PR adds a no-op `SetScreen` implementation on `*BrowserWindow` that returns the receiver, matching the existing fluent no-op pattern already used by sibling setters like `SetTitle`, `SetMinSize`, and `SetMaxSize`. Moving a browser client to a particular native screen isn't a meaningful operation, so a no-op is the correct behavior here, consistent with how the rest of the server-mode adapter handles native-only window operations.

Fixes [#5262](https://github.com/wailsapp/wails/issues/5262).

No new dependencies.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Reproduced the failure on `master` and verified the fix with:

```bash
cd v3/examples/dock
go build -tags server .   # fails before, succeeds after
go build .                # default (non-server) build still succeeds
```

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [X] macOS
- [ ] Linux
      
If you checked Linux, please specify the distro and version.
  
## Test Configuration

```
 Wails (v3.0.0-alpha.79)  Wails Doctor

# System

┌──────────────────────────────────────────────────┐
| Name          | MacOS                            |
| Version       | 15.7.4                           |
| ID            | 24G517                           |
| Branding      | Sequoia                          |
| Platform      | darwin                           |
| Architecture  | arm64                            |
| Apple Silicon | true                             |
| CPU           | Apple M1 Pro                     |
| CPU 1         | Apple M1 Pro                     |
| CPU 2         | Apple M1 Pro                     |
| GPU           | 16 cores, Metal Support: Metal 3 |
| Memory        | 32 GB                            |
└──────────────────────────────────────────────────┘

# Build Environment

┌────────────────────────────────┐
| Wails CLI    | v3.0.0-alpha.79 |
| Go Version   | go1.25.1        |
| -buildmode   | exe             |
| -compiler    | gc              |
| CGO_CFLAGS   |                 |
| CGO_CPPFLAGS |                 |
| CGO_CXXFLAGS |                 |
| CGO_ENABLED  | 1               |
| CGO_LDFLAGS  |                 |
| GOARCH       | arm64           |
| GOARM64      | v8.0            |
| GOOS         | darwin          |
└────────────────────────────────┘

# Dependencies

┌──────────────────────────────────────────────────────────────────────────────┐
| npm             | 10.9.4                                                     |
| *NSIS           | Not Installed. Install with `brew install makensis`.       |
| Xcode cli tools | 2410                                                       |
| docker          | *Docker version 29.0.1, build eedd969 (daemon not running) |
|                                                                              |
└────────────────────────── * - Optional Dependency ───────────────────────────┘

# Checking for issues

 SUCCESS  No issues found
```

# Checklist:

- [ ] (v2 only) I have updated `website/src/pages/changelog.mdx` with details of this PR (v3 changelog entries are added automatically)
- [X] My code follows the general coding style of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (N/A)
- [ ] I have made corresponding changes to the documentation (N/A)
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (N/A)
- [X] New and existing unit tests pass locally with my changes
   - One pre-existing failure in internal/commands (TestGenerateIcon) requires full Xcode.app for actool; unrelated to this change.

## Pre-existing failures unrelated to this change

While running the test suite to verify this PR, two pre-existing failures surfaced. Both reproduce on master without the patch applied:

- **`TestGenerateIcon`** in `v3/internal/commands` — fails with `mac asset generation is only supported on macOS` despite running on macOS. Appears to require the full Xcode.app bundle (for `actool`); my local environment only has Xcode CLI tools installed.
- **`go vet` failure** in `v3/pkg/application/websocket_server.go:67` — `(*App).error call has arguments but no formatting directives`. Only surfaces under `-tags server`, which suggests another instance of the same server-mode bit-rot that #5262 is fixing. Worth a follow-up PR.

Neither failure is in code touched by this PR, and `go test -tags server -vet=off ./...` passes cleanly otherwise.

## Summary by CodeRabbit

* **New Features**
  * Extended browser window API with a new chainable method for screen configuration capabilities.

### CODE REVIEW

**Comment by leaanthony** [comment]
✅ **Triaged by Wails PR Reviewer**

This PR has been reviewed and accepted. Test sub-issues have been created for all platforms.

**Head Ref OID: `e3a5f6952ff8834640dd97986927b451684b7521`**

---
*This comment serves as a signature that this PR has been triaged. Future runs will skip this PR based on the headRefOid.*

**Comment by leaanthony** [comment]
**Tested on Linux (Ubuntu 24.04 LTS)** — verdict: ✓ PASS

**Platform:** Ubuntu 24.04.4 LTS / WebKit2GTK v2.50.4 / Go 1.25.0
**Commit:** `e3a5f6952ff8834640dd97986927b451684b7521`

| Check | Result |
|-------|--------|
| `go build -tags server ./pkg/application/...` | ✅ PASS |
| Full `./...` build (iOS failure) | ⚠️ pre-existing unrelated failure, not caused by this PR |
| Unit tests (`pkg/application` core) | ✅ 16 pass |
| Display-dependent tests | ⚠️ 5 fail (headless env, pre-existing) |
| Visual smoke (Dialogs Demo) | ✅ window rendered correctly on GNOME |

The `-tags server` build now compiles cleanly on Linux with the `SetScreen` stub in place. Safe to merge on Linux.

**Comment by leaanthony** [comment]
My bad! I accidentally fixed this before seeing this 🙏 Thanks for bringing it up.

**Comment by josh-padnick** [comment]
No worries! Glad it got fixed, and thanks for the prompt response!
